---
- name: Create Portainer
  hosts: all
  become: True
  
  tasks:
    - name: Pull Portainer container
      community.docker.docker_image:
        name: "portainer/portainer-ce:latest"
        source: pull

    - name: Create Portainer volume
      community.docker.docker_volume:
        name: portainer_data
        state: present
      
    - name: Create Portainer container
      community.docker.docker_container:
        name: "portainer"
        image: "portainer/portainer-ce:latest"
        ports:
          - 9443:9443
        #  - 8000:8000
        volumes:
          - portainer_data:/data
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: "always"
        detach: true