---
- name: Create Portainer Agent
  hosts: all
  become: True
  
  tasks:
    - name: Pull Portainer Agent container
      community.docker.docker_image:
        name: "portainer/agent:2.19.5"
        source: pull

    - name: Create Portainer volume
      community.docker.docker_volume:
        name: portainer_data
        state: present
      
    - name: Create Portainer container
      community.docker.docker_container:
        name: "portainer_agent"
        image: "portainer/agent:2.19.5"
        ports:
          - 9001:9001
        volumes:
          - /var/lib/docker/volumes:/var/lib/docker/volumes
          - /var/run/docker.sock:/var/run/docker.sock
        restart_policy: "always"
        detach: true